import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className="w-full bg-yellow-400 p-4 flex items-center justify-between">
					<div className="flex items-center space-x-2">
						<h1 className="text-white text-2xl font-bold">
							The Lysefeldt Gallery
						</h1>
					</div>
				</header>
				{children}
			</body>
		</html>
	);
}
